alimentation/urls.py
from django.db.models.base import Model
from django.db.models.fields import DateField
from django.urls import path
from .views import AlimentDetailView,AlimentationListView,AlimentationDeleteView,LoginFormView,InscriptionFormView,ProfileUpdateView,AlimeantionDayArchiveView,HistoriqueListView,MDPChangerFormView,MDPResetFormView,MailResetView
app_name = "alimentation"
urlpatterns = [
    path('',AlimentationListView.as_view(),name="index"),
    path('historique/<int:year>-<int:month>-<int:day>/',AlimeantionDayArchiveView.as_view(),name="historique-alimenation"),
    path('detail/<int:pk>',AlimentDetailView.as_view(),name="detail"),
    path('delete/<int:pk>',AlimentationDeleteView.as_view(),name="delete"),
    path('historique/',HistoriqueListView.as_view(),name="historique"),
    path('accounts/inscription',InscriptionFormView.as_view(),name="inscription"),
    path('accounts/login',LoginFormView.as_view(),name="login"),
    path('accounts/mdpreset',MDPResetFormView.as_view(),name="mdp_reset"),
    path('accounts/mail_reset',MailResetView.as_view(),name="mail_reset"),
    path('accounts/mdpchanger/<uidb64>/<token>/',MDPChangerFormView.as_view(),name="mdp_changer"),
    path('profile/modifier/<int:pk>',ProfileUpdateView.as_view(),name="profile_update"),
]

suivie_alim/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("alimentation.urls")),

]
urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alimentation/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
class Aliment(models.Model):
    nom = models.CharField(max_length=150)
    calorie = models.IntegerField()
    lipides = models.FloatField()
    cholestérol = models.FloatField()
    protéines = models.FloatField()
    potassium = models.FloatField()
    glucides = models.FloatField()
    image = models.FileField(upload_to="aliment/", max_length=250,default="pas_d'image_disponible.png")
    def __str__(self):
        return self.nom
    def get_absolute_url(self):
        return reverse("aliment_detail", kwargs={"pk": self.pk})
class Alimentation(models.Model):
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE)
    aliment = models.ForeignKey(Aliment, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    def __str__(self):
        return self.utilisateur.username

class Profile(models.Model):
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE)
    calorie = models.IntegerField()
    lipides = models.FloatField()
    cholestérol = models.FloatField()
    protéines = models.FloatField()
    potassium = models.FloatField()
    glucides = models.FloatField()
    def __str__(self):
        return self.utilisateur.username
    def get_absolute_url(self):
        return reverse("profile_alimentation.html", kwargs={"pk": self.pk})

alimentation/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,PasswordResetForm
from django.contrib.auth.models import User
class InscriptionForm(UserCreationForm):
    nom = forms.CharField(max_length=50, required=True)
    prenom = forms.CharField(max_length=50, required=True)
    field_order = ["nom","prenom"]
    def __init__(self, *args,**kwargs):
        super(InscriptionForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"]="form-control"
class LoginForm(AuthenticationForm):
    def __init__(self, *args,**kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"]="form-control"
class MDPResetform(PasswordResetForm):
    def __init__(self, *args,**kwargs):
        super(MDPResetform, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"]="form-control"

alimentation/views.py
from typing import ItemsView
from django.conf.urls import url
from django.urls import reverse_lazy
from django.shortcuts import render, reverse,redirect
from django.views.generic import DetailView,ListView,DeleteView,FormView,UpdateView,TemplateView
from django.views.generic.base import TemplateView
from .models import Aliment,Alimentation,Profile
from django.db.models import  Sum,Count
from datetime import date
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import InscriptionForm,LoginForm,MDPResetform
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.views.generic.dates import DayArchiveView
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.contrib.auth.views import PasswordResetConfirmView,PasswordResetDoneView
class InscriptionFormView(FormView):
    form_class = InscriptionForm
    template_name = "compte/inscription.html"
    success_url = 'login'
    def form_valid(self,form):
        user = User.objects.create(username=form.cleaned_data["username"],password=form.cleaned_data["password2"],first_name=form.cleaned_data["nom"],last_name=form.cleaned_data["prenom"])
        profile = Profile.objects.create(utilisateur=user,calorie=2000,lipides=20,cholestérol=0.3,protéines=60,potassium=3.5,glucides=190)
        return super().form_valid(form)
class LoginFormView(FormView):
    form_class = LoginForm
    template_name = "compte/login.html"
    success_url = '/'
    def form_valid(self,form):
        user = authenticate(username=form.cleaned_data["username"],password=form.cleaned_data["password"])
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)
class MDPResetFormView(FormView):
    form_class = MDPResetform
    template_name = "compte/changer-mdp.html"
    success_url = 'mail_reset'
    def form_valid(self,form):
        utilisateurs = User.objects.filter(email=form.cleaned_data.get('email'))
        if utilisateurs.exists():
            for utilisatateur in  utilisateurs:
                email_template_name = "mail/reset_mail.txt"
                mail_data = {
                        "email":utilisatateur.email,
                        'domain':'127.0.0.1:8000',
                        'site_name': 'CaraAlim',
                        "uid": urlsafe_base64_encode(force_bytes(utilisatateur.pk)),
                        "user": utilisatateur,
                        'token': default_token_generator.make_token(utilisatateur),
                        'protocol': 'http',
                        }
                content = render_to_string(email_template_name,mail_data)
                print(content)
                send_mail(subject="Reset du mot de passe",message=content,from_email="guyanebbc@gmail.com",recipient_list=[f"{form.cleaned_data.get('email')}"])
        return super().form_valid(form)    

class MDPChangerFormView(PasswordResetConfirmView):
    template_name = "compte/changer-mdp.html"
    success_url = '/accounts/login'
    def form_valid(self,form):
        User.objects.filter(id=self.user.id).update(password=form.cleaned_data.get('new_password1'))
        return super().form_valid(form)    
    def get_form(self):
        form = super(MDPChangerFormView, self).get_form()
        for visible in form.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
        return form
class AlimentDetailView(LoginRequiredMixin,DetailView):
    model = Aliment
    template_name = "alimentation/aliment_detail.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["liste_profile"] = Profile.objects.all()
        return context
    
class AlimentationListView(LoginRequiredMixin,ListView):
    model = Alimentation
    template_name = "alimentation/alimentation_list.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["liste_aliments"] = Aliment.objects.all()
        context["liste_profile"] = Profile.objects.all()
        context["liste_consomation"] = Alimentation.objects.filter(utilisateur=self.request.user.id,date=date.today())
        liste_totale_valeur = []
        liste_profile_valeur = []
        if Alimentation.objects.filter(utilisateur=self.request.user.id,date=date.today()).exists():
            context["liste_totale"] =  Alimentation.objects.filter(utilisateur=self.request.user.id,date=date.today()).aggregate(Count("aliment__nom"),Sum("aliment__calorie"),Sum("aliment__lipides"),Sum("aliment__cholestérol"),Sum("aliment__protéines"),Sum("aliment__potassium"),Sum("aliment__glucides"))
            liste_totale_valeur = []
            liste_profile_valeur = []
            for item in context["liste_profile"].values() :
                liste_profile_valeur.append(item)
            for item in context["liste_totale"].values() :
                liste_totale_valeur.append(item)
            liste_totale_valeur = liste_totale_valeur[1:]
            liste_profile_valeur = list(liste_profile_valeur[0].values())
            liste_profile_valeur = liste_profile_valeur[2:]
            result = map(lambda x, y: round((x / y)*100,2), liste_totale_valeur, liste_profile_valeur)
            context["liste_pourcentage"] = list(result)
        return context
    def post(self,request) :
        if request.method == "POST" :
            aliment_consomme = request.POST["ajouter-aliment"]
            if aliment_consomme:
                aliment_cosomme_utilisateur = Aliment.objects.get(id=aliment_consomme)
                utilisateur = request.user
                alimentation = Alimentation(utilisateur=utilisateur,aliment=aliment_cosomme_utilisateur)
                alimentation.save()
        return HttpResponseRedirect(reverse('alimentation:index'))
class ProfileUpdateView(LoginRequiredMixin,UpdateView):
    model = Profile
    template_name = "alimentation/profile_update.html"
    fields = ["calorie","lipides","cholestérol","protéines","potassium","glucides"]
    success_url = "/"
    def get_form(self):
        form = super(ProfileUpdateView, self).get_form()
        for visible in form.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
        return form
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["liste_profile"] = Profile.objects.all()
        return context
class AlimentationDeleteView(LoginRequiredMixin,DeleteView):
    model = Alimentation
    template_name = "alimentation/aliment_delete.html"
    success_url = reverse_lazy("alimentation:index")
class AlimeantionDayArchiveView(DayArchiveView):
    date_field = "date"
    allow_future = False
    month_format = "%m"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["liste_profile"] = Profile.objects.all()
        context["liste_totale"] =  Alimentation.objects.filter(utilisateur=self.request.user.id,date=kwargs.get("day")).aggregate(Count("aliment__nom"),Sum("aliment__calorie"),Sum("aliment__lipides"),Sum("aliment__cholestérol"),Sum("aliment__protéines"),Sum("aliment__potassium"),Sum("aliment__glucides"))
        liste_totale_valeur = []
        liste_profile_valeur = []
        for item in context["liste_profile"].values() :
                liste_profile_valeur.append(item)
        for item in context["liste_totale"].values() :
            liste_totale_valeur.append(item)
        liste_totale_valeur = liste_totale_valeur[1:]
        liste_profile_valeur = list(liste_profile_valeur[0].values())
        liste_profile_valeur = liste_profile_valeur[2:]
        result = map(lambda x, y: round((x / y)*100,2), liste_totale_valeur, liste_profile_valeur)
        context["liste_pourcentage"] = list(result)
        return context
    def get_queryset(self):
        return  Alimentation.objects.filter(utilisateur=self.request.user)

class MailResetView(TemplateView):
    template_name = "compte/base.html"
    
class HistoriqueListView(LoginRequiredMixin,ListView):
    template_name = "alimentation/historique_list.html"
    def get_queryset(self):
        return Alimentation.objects.filter(utilisateur=self.request.user).exclude(date=date.today()).distinct().values("date")
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["liste_profile"] = Profile.objects.all()
        return context

alimentation/templates/alimentation/aliment_delete.html
{% extends 'alimentation/base.html' %}
{% block contenue %}
<form class="text-center" method="post">
    {% csrf_token %}
    {{form}}
    <p>Vous voulez vraiment suprimer cette aliment de votre liste.</p>
    <button class="btn btn-danger" type="submit">supprimer</button>
    <a href="{% url 'alimentation:index' %}" class="btn btn-primary">annuler</a>
</form>
{% endblock  %}

alimentation/templates/alimentation/aliment_detail.html
{% extends 'alimentation/base.html' %}
{% block contenue %}
    <div class="row">
        <div class="col">
            <h2 class="display-4 text-uppercase text-center">{{ object.nom }}</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <img  class="img-fluid" src="{{ object.image.url }}" alt="{{ object.nom }}">
        </div>
        <div class="col">
            <table class="table">
                <thead class="table-dark">
                    <tr>
                            <th>Nom</th>
                            <th>Quantité</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Calorie</td>
                        <td>{{object.calorie}}</td>
                    </tr>
                    <tr>
                        <td>Lipides</td>
                        <td>{{object.lipides}}</td>
                    </tr>
                    <tr>
                        <td>Cholestérol</td>
                        <td>{{object.cholestérol}}</td>
                    </tr>
                    <tr>
                        <td>Protéines</td>
                        <td>{{object.protéines}}</td>
                    </tr>
                    <tr>
                        <td>Potassium</td>
                        <td>{{object.potassium}}</td>
                    </tr>
                    <tr>
                        <td>Glucides</td>
                        <td>{{object.glucides}}</td>
                    </tr>
                </tbody>
              </table>
              <canvas id="myChart" width="400" height="400"></canvas>
        </div>
    </div>
{% endblock  %}
{% block body %}
<script>
    const data = {
        labels: [
          'Lipides',
          'Cholestérol',
          'Protéines',
          'Potassium ',
          'Glucides'
        ],
        datasets: [{
          label: 'Valeur energetique',
          data: [{{object.lipides|escapejs}},{{object.cholestérol|escapejs}},{{object.protéines|escapejs}},{{object.potassium|escapejs}},{{object.glucides|escapejs}}],
          backgroundColor: [
            'rgb(241, 196, 15)',
            'rgb(183, 149, 11)',
            'rgb(255, 0, 0 )',
            'rgb(198, 230, 236)',
            'rgb(255, 146, 0)'
          ],
          hoverOffset: 4
        }]
      };
    var ctx = document.getElementById('myChart'); 
    var myChart = new Chart(ctx, {
        type: 'pie',
        data: data,
    });
</script>
{% endblock  %}

alimentation/templates/alimentation/alimentation_archive_day.html
{% extends 'alimentation/alimentation_list.html' %}
{% block formulaire %}

{% endblock formulaire %}
{% block contenue %}
    {% with object_list as liste_consomation %}
            {{ block.super }}
    {% endwith %}
    {% block btn_effacer_tab %} {% endblock btn_effacer_tab %}
{% endblock contenue %}

alimentation/templates/alimentation/alimentation_list.html
{% extends 'alimentation/base.html' %}
{% load static %}
{% block contenue %}
{% block formulaire %}
<form method="POST" class="row">
    {% csrf_token %}
    <div class="col-md-9 col-sm-12 "}>
        <select name="ajouter-aliment" id="select-aliment" class="form-select form-select-lg mb-3" aria-label=".form-select-lg example">
                {% for aliment in liste_aliments %}
                <option value="{{aliment.id}}">{{aliment.nom}}</option>
                {% endfor %}    
        </select>
    </div>
    <div class="col-md-3 col-sm-12 mb-3">
        {% for aliment in liste_aliments %}
        {% if aliment.id == 1 %}
        <a  href="{% url 'alimentation:detail' aliment.id %}" id="aliment_{{aliment.id}}" class="btn btn-primary btn-info-alimentation btn-lg visible" target="out_blank"type="submit"><i class="bi bi-info-circle"></i></a>
        {% else %}
        <a  href="{% url 'alimentation:detail' aliment.id %}" id="aliment_{{aliment.id}}"class="btn btn-primary btn-lg btn-info-alimentation visually-hidden" target="out_blank" type="submit"><i class="bi bi-info-circle"></i></a>
        {% endif %}
        {% endfor %}    
        <button class="btn btn-primary btn-lg" type="submit"><i class="bi bi-calendar-plus"></i></button>
    </div>
</form>
{% endblock formulaire %}
<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th scope="col">aliment</th>
                    <th scope="col">calorie</th>
                    <th scope="col">lipides</th> 
                    <th scope="col">cholestérol</th> 
                    <th scope="col">protéines</th> 
                    <th scope="col">potassium</th> 
                    <th scope="col">glucides</th> 
                </tr>
            </thead>
            <tbody>
                {% for object in liste_consomation %}
                <tr>
                    <td scope="col">{{object.aliment.nom}}</td>
                    <td scope="col">{{object.aliment.calorie|floatformat}}</td>
                    <td scope="col">{{object.aliment.lipides|floatformat}}</td> 
                    <td scope="col">{{object.aliment.cholestérol|floatformat}}</td> 
                    <td scope="col">{{object.aliment.protéines|floatformat}}</td> 
                    <td scope="col">{{object.aliment.potassium|floatformat}}</td> 
                    <td scope="col">{{object.aliment.glucides|floatformat}}</td> 
                    {% block btn_effacer_tab %}<td><a href="{% url 'alimentation:delete' object.id %}" class="btn btn-outline-danger"><i class="bi bi-trash"></i></button></td>{% endblock btn_effacer_tab %}
                </tr>
                {% endfor %}
                <tr>
                    <td scope="col">Totale : {{liste_totale.aliment__nom__count |floatformat}}</td>
                    <td scope="col">{{liste_totale.aliment__calorie__sum |floatformat}}</td>
                    <td scope="col">{{liste_totale.aliment__lipides__sum |floatformat}}</td> 
                    <td scope="col">{{liste_totale.aliment__cholestérol__sum |floatformat}}</td> 
                    <td scope="col">{{liste_totale.aliment__protéines__sum |floatformat}}</td> 
                    <td scope="col">{{liste_totale.aliment__potassium__sum |floatformat}}</td> 
                    <td scope="col">{{liste_totale.aliment__glucides__sum |floatformat}}</td> 
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-5 mx-auto">
        <canvas id="myChart"></canvas>
    </div>
</div>
<div class="row">
    <div class="col">
        <canvas id="pourcentageBar"></canvas>
    </div>
</div>

{% endblock  %}
{% block body %}
<script>
liste_aliment = document.getElementById("select-aliment")
if(liste_aliment){
   liste_aliment.onchange = function() {changerBouttonInfo()};
}

function changerBouttonInfo() {
    var id_aliment = document.getElementById("select-aliment").value;
    var ancien_boutton = document.getElementsByClassName("btn-info-alimentation visible");
    ancien_boutton[0].classList.add("visually-hidden");
    ancien_boutton[0].classList.remove("visible");
    var nouveau_boutton = document.getElementById("aliment_"+id_aliment);
    nouveau_boutton.classList.remove("visually-hidden");
    nouveau_boutton.classList.add("visible");
}
    const data_totale = {
        labels: [
          'Lipides',
          'Cholestérol',
          'Protéines',
          'Potassium ',
          'Glucides'
        ],
        datasets: [{
          label: 'Valeur energetique',
          data: [{{liste_totale.aliment__lipides__sum|escapejs}},{{liste_totale.aliment__cholestérol__sum|escapejs}},{{liste_totale.aliment__protéines__sum|escapejs}},{{liste_totale.aliment__potassium__sum|escapejs}},{{liste_totale.aliment__glucides__sum|escapejs}}],
          backgroundColor: [
            'rgb(241, 196, 15)',
            'rgb(183, 149, 11)',
            'rgb(255, 0, 0 )',
            'rgb(198, 230, 236)',
            'rgb(255, 146, 0)'
          ],
          hoverOffset: 4
        }]
      };
    const data_pourcentage = {
    labels:  [
          'Lipides',
          'Cholestérol',
          'Protéines',
          'Potassium ',
          'Glucides'
        ],
    datasets: [{
        label: 'Pourcentage %',
        data: {{liste_pourcentage|escapejs}},
        backgroundColor: [
        'rgba(255, 99, 132, 0.2)',
        'rgba(255, 159, 64, 0.2)',
        'rgba(255, 205, 86, 0.2)',
        'rgba(75, 192, 192, 0.2)',
        'rgba(54, 162, 235, 0.2)'
        ],
        borderColor: [
        'rgb(255, 99, 132)',
        'rgb(255, 159, 64)',
        'rgb(255, 205, 86)',
        'rgb(75, 192, 192)',
        'rgb(54, 162, 235)'
        ],
        borderWidth: 1
    }]
    };
    var ctx = document.getElementById('myChart'); 
    var myChart = new Chart(ctx, {
        type: 'pie',
        data: data_totale,
    });
    var cpourcentage = document.getElementById('pourcentageBar'); 
    var pourcentageBar = new Chart(cpourcentage, {
        type: 'bar',
        data: data_pourcentage,
        options: {
            scales: {
            y: {
                beginAtZero: true
            }
            }
        },
        });
</script>
{% endblock  %}

alimentation/templates/alimentation/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/alimentation.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <title>Suivie alimentation</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Suvis alimentation</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url 'alimentation:index' %}">Aujourd'huis</a>
              <a class="nav-link" href="{% url 'alimentation:profile_update' liste_profile.0.id %}">Profile</a>
              <a class="nav-link" href="{% url 'alimentation:historique' %}">Historique</a>
            </div>
          </div>
        </div>
    </nav>
    <div class="container">
    {% block contenue %}
    {% endblock  %}
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/chart.js' %}"></script>
    {% block body %}
    {% endblock  %}
</body>
</html>

alimentation/templates/alimentation/historique_list.html
{% extends 'alimentation/base.html' %}
{% load static %}
{% block contenue %}
<div class="row">
    <div class="col-4 mx-auto">
        <h2 class="text-center">Historique</h2>
        <ul class="list-group text-center">
            {% for item in object_list  %}
            <li class="list-group-item">{{item.date}}<a class="btn btn-primary" href="{% url 'alimentation:historique-alimenation' item.date|date:"Y" item.date|date:"m" item.date|date:"d"  %}">voir</a></li>
            {% endfor %}
        </ul>
    </div>

</div>
{% endblock contenue %}

alimentation/templates/alimentation/profile_update.html
{% extends 'alimentation/base.html' %}
{% block contenue %}
<div class="row">
    <div class="col-6 mx-auto">
        {% include "formulaire/normale_form.html" %}
    </div>
</div>
{% endblock  %}